import { StyleSheet, Platform, StatusBar } from 'react-native';
import { THEME } from '../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.background,
    // Top inset for legacy screens not yet migrated to SafeScreen.
    // SafeScreen does NOT use this container (it applies insets.top itself) to avoid double-applying.
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: THEME.background,
    padding: 24,
  },
  header: {
    height: 60,
    backgroundColor: THEME.background,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: THEME.text,
  },
  headerTitleHighlight: {
    fontSize: 12,
    fontWeight: 'bold',
    color: THEME.primary,
  },
  headerAction: {
    fontSize: 15,
    fontWeight: '600',
  },
  splashLogoImage: {
    width: 100,
    height: 100,
    marginBottom: 24,
  },
  logoEmoji: {
    fontSize: 64,
    marginBottom: 20,
  },
  logoTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  logoTitleSub: {
    fontSize: 16,
    color: THEME.primary,
    fontWeight: 'bold',
    marginTop: 6,
    letterSpacing: 2.5,
    textTransform: 'uppercase',
  },
  dashboardContainer: {
    flex: 1,
  },
  dashboardContentContainer: {
    paddingVertical: 16,
  },
  dashboardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionHeader: {
    fontSize: 14,
    fontWeight: 'bold',
    color: THEME.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  refreshText: {
    fontSize: 13,
    color: THEME.primary,
    fontWeight: 'bold',
  },
  rescanBtn: {
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  rescanBtnText: {
    fontSize: 13,
    fontWeight: 'bold',
  },

  // Carousel slides
  carouselScrollView: {
    marginVertical: 8,
  },
  carouselCard: {
    borderRadius: 16,
    padding: 20,
    height: 190,
    justifyContent: 'space-between',
    overflow: 'hidden',
    position: 'relative',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
  },
  cardGlow1: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    top: -45,
    right: -45,
    opacity: 0.5,
  },
  cardGlow2: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    bottom: -35,
    left: -35,
    opacity: 0.5,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 2,
  },
  cardBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  cardBadgeText: {
    fontSize: 9,
    color: '#FFF',
    fontWeight: '600',
  },
  walletMenuItem: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  walletMenuText: {
    fontSize: 15,
    color: THEME.text,
    fontWeight: '500',
    textAlign: 'center',
  },
  cardAliasName: {
    fontSize: 16,
    color: '#FFF',
    fontWeight: 'bold',
  },
  cardAddressRow: {
    marginTop: 4,
    marginBottom: 6,
    zIndex: 2,
  },
  cardAddressText: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '500',
  },
  cardKRWBalance: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFF',
    marginVertical: 6,
    zIndex: 2,
  },
  cardActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  cardActionBtn: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 3,
  },
  cardActionBtnText: {
    fontSize: 11,
    color: '#FFF',
    fontWeight: '600',
  },
  indicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 10,
  },
  indicatorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    marginHorizontal: 3,
  },
  indicatorDotActive: {
    backgroundColor: THEME.primary,
    width: 14,
  },

  // Asset list
  assetHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  assetSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: THEME.text,
  },
  assetListContainer: {
    marginBottom: 20,
  },
  assetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: THEME.cardBg,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: THEME.border,
    marginBottom: 8,
  },
  assetIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  assetIconText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  assetIconContainer: {
    width: 38,
    height: 38,
    position: 'relative',
    marginRight: 12,
    overflow: 'visible',
  },
  assetIconImageWrapper: {
    width: 38,
    height: 38,
    borderRadius: 19,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#16161A',
  },
  assetIconImage: {
    width: 38,
    height: 38,
  },
  assetIconTextOverlay: {
    position: 'absolute',
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textTransform: 'uppercase',
  },
  assetChainBadge: {
    position: 'absolute',
    // Old Android (API 28) mis-renders bottom/right and absolute positions outside the parent,
    // so place the badge via top/left inside the parent (38x38) bounds.
    top: 23,
    left: 23,
    width: 15,
    height: 15,
    borderRadius: 7.5,
    borderWidth: 1,
    borderColor: '#0C0C0E',
    backgroundColor: '#0C0C0E',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
    elevation: 4,
  },
  assetChainBadgeImg: {
    // Chain logos (Logo_BSC/BASE) are already circular, so don't clip them
    // (avoids the API 28 bug where a small image inside a round clip wouldn't render).
    width: 13,
    height: 13,
  },
  assetNameCol: {
    flex: 1,
  },
  assetTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: THEME.text,
  },
  assetSubTitle: {
    fontSize: 11,
    color: THEME.textMuted,
    marginTop: 3,
  },
  assetValueCol: {
    alignItems: 'flex-end',
  },
  assetBalanceVal: {
    fontSize: 15,
    fontWeight: 'bold',
    color: THEME.text,
  },
  assetTickerText: {
    fontSize: 10,
    color: THEME.textMuted,
    marginTop: 3,
  },

  // Modal structure
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: THEME.cardBg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: THEME.border,
    width: '100%',
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
    paddingBottom: 10,
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: THEME.text,
  },
  modalCloseButton: {
    padding: 4,
  },
  modalCloseButtonText: {
    fontSize: 18,
    color: THEME.textMuted,
  },
  modalLabel: {
    fontSize: 13,
    color: THEME.textMuted,
    marginBottom: 6,
  },
  historyModalSubHeader: {
    fontSize: 11,
    color: THEME.textMuted,
    marginTop: 2,
  },
  gridActionBtn: {
    backgroundColor: '#24242A',
    borderRadius: 10,
    minHeight: 52,
    paddingVertical: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: THEME.border,
  },
  gridActionText: {
    fontSize: 13,
    fontWeight: '600',
    color: THEME.text,
  },

  // Device security lock
  lockContainer: {
    flex: 1,
    backgroundColor: THEME.background,
    justifyContent: 'space-between',
    paddingVertical: 60,
    paddingHorizontal: 24,
  },
  lockContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lockIconCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#1E1E24',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  lockIconEmoji: {
    fontSize: 38,
  },
  lockTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: THEME.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  lockSubtitle: {
    fontSize: 14,
    color: THEME.textMuted,
    textAlign: 'center',
    paddingHorizontal: 20,
    lineHeight: 20,
  },
  lockErrorContainer: {
    marginTop: 18,
  },
  lockErrorText: {
    fontSize: 13,
    color: THEME.danger,
    textAlign: 'center',
  },
  lockBottomContainer: {
    width: '100%',
  },
  lockButton: {
    backgroundColor: THEME.primary,
    height: 54,
    borderRadius: 27,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lockButtonText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#000000',
  },
  lockHint: {
    fontSize: 13,
    color: THEME.textMuted,
    textAlign: 'center',
    lineHeight: 18,
  },

  // Forms & card inputs
  card: {
    backgroundColor: THEME.cardBg,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  fieldLabel: {
    fontSize: 13,
    color: THEME.textMuted,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#0F0F12',
    color: '#FFF',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  submitButton: {
    backgroundColor: THEME.primary,
    borderRadius: 10,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
  },
  btn: {
    backgroundColor: THEME.primary,
    borderRadius: 10,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
  },
  btnDisabled: {
    opacity: 0.5,
  },
  errorCard: {
    backgroundColor: 'rgba(255, 59, 48, 0.1)',
    borderColor: THEME.danger,
  },
  errorText: {
    color: THEME.danger,
    fontSize: 13,
    lineHeight: 18,
  },
  infoText: {
    color: THEME.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },

  // PSBT result display
  psbtRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  psbtRowLabel: {
    color: THEME.textMuted,
    fontSize: 13,
    flexShrink: 0,
  },
  psbtRowVal: {
    color: THEME.text,
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
    textAlign: 'right',
  },

  // Fee presets
  feeTierBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.border,
    alignItems: 'center',
  },
  feeTierLabel: {
    color: THEME.text,
    fontSize: 14,
    fontWeight: '600',
  },
  feeTierVal: {
    color: THEME.textMuted,
    fontSize: 11,
    marginTop: 2,
  },

  // QR scan
  scanBtn: {
    marginTop: 12,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanBtnText: {
    color: THEME.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  scanCancelBtn: {
    position: 'absolute',
    bottom: 48,
    alignSelf: 'center',
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  scanCancelText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
  },

  // Transaction card
  txCard: {
    backgroundColor: THEME.cardBg,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  txAmount: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  txArrow: {
    fontSize: 13,
    fontWeight: 'bold',
    marginLeft: 6,
  },
  txDirection: {
    fontSize: 13,
    fontWeight: 'bold',
  },
  txBlock: {
    fontSize: 12,
    color: THEME.textMuted,
  },
  txDate: {
    fontSize: 11,
    color: THEME.textMuted,
    marginTop: 2,
  },
  txIdText: {
    fontSize: 11,
    color: THEME.textMuted,
    fontFamily: 'monospace',
    backgroundColor: 'rgba(0,0,0,0.2)',
    padding: 8,
    borderRadius: 6,
  },
  copyBtn: {
    backgroundColor: 'rgba(255, 153, 0, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 153, 0, 0.3)',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginTop: 8,
  },
  copyBtnText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: THEME.primary,
  },

  // Address list jump/pagination
  addrJumpRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 8,
  },
  addrJumpInput: {
    flex: 1,
    backgroundColor: THEME.cardBg,
    color: '#FFF',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 42,
    fontSize: 13,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  addrJumpBtn: {
    borderRadius: 8,
    width: 60,
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addrJumpBtnText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#000',
  },
  addrItem: {
    backgroundColor: THEME.cardBg,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  addrItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addrIdx: {
    fontSize: 11,
    fontWeight: 'bold',
  },
  addrPath: {
    fontSize: 11,
    color: THEME.textMuted,
  },
  addrBalance: {
    fontSize: 11,
    fontWeight: 'bold',
  },
  addrUsedBadge: {
    fontSize: 10,
    fontWeight: '700',
    color: '#E0A030',
    backgroundColor: 'rgba(224,160,48,0.15)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  addrStr: {
    fontSize: 12,
    color: THEME.text,
    marginTop: 4,
  },
  addrPageRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: THEME.border,
    backgroundColor: THEME.background,
  },
  addrPageBtn: {
    backgroundColor: THEME.cardBg,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  addrPageBtnText: {
    fontSize: 12,
    color: THEME.text,
    fontWeight: '600',
  },
  addrPageInfo: {
    fontSize: 12,
    color: THEME.textMuted,
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: 12,
  },
  emptyText: {
    fontSize: 14,
    color: THEME.textMuted,
  },
  scanningText: {
    fontSize: 12,
    color: THEME.textMuted,
  },
  editAssetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
    paddingHorizontal: 16,
  },
  visibilityToggleBtn: {
    paddingRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#444',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxCheck: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: 'bold',
  },
  reorderControls: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  reorderBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#242429',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: THEME.border,
  },
  reorderBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
});
